### ISSUE TITLE
Order workflow ist not exposed

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#21]
Accessing /api/rest/latest/orders/752 does not expose "workflow" anymore. Break after upgrading to Oro Platform version 2?

**Comment by 24198** [comment]
Hi @clicktrend,

Thanks for reporting! We've come to the realisation that the Worfklow is not assigned to an entity anymore and our tests failed to catch this case. We did however just pushed a change which exposes the 'workflowItems' again. Since the upgrade to 2.0.0 we also had to take into account that there could be more than workflow assigned on a single entity so the key 'workflowItem' and 'workflowStep' are deprecated since the last push and being replaced by a single key 'workflowItems' with the key 'currentStep' which is the step the workflow is in at that very moment.

Now all we have left to do is update the bridge to comply with this new key.

Kind Regards,


Jaimy Casteleijn
