### ISSUE TITLE
Marello address: Integrity constraint violation

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#23]
Hi,

forcing schema update changes "updated" field in marello_address to "NOT NULL". But migration allows NULL. Facing this error:

```
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'updated' cannot be null in /Sites/marello/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
```

Entity MarelloAddress has to handle this error.

**Comment by 24198** [comment]
Hi @clicktrend,

We believe the update of the migration is correct, but since it already has data it will fail miserably. We recommend to use the `php app/console oro:platform:update --env=prod --force` in order to fix the existing data. We've created a migration which will update the current `updated` and `updated_at` `NULL` values in the `marello_address` and `marello_product_product` tables. This should help with issue #24 as well.

Hope this helps!

Kind Regards,

Jaimy Casteleijn

**Comment by 24198** [comment]
Issue should be solved since the migration solves the not null integrity constraint violation by updating the updated fields. Closing issue during inactivity.
