### ISSUE TITLE
Update ORO Platform version

### ISSUE THREAD

**Issue by sagikazarmark** [marellocommerce/marello#3]
The latest ORO Platform version came with quite a few interesting features (for example more simpler configurations). AFAIK the newest (1.10) version is close. Since Marello is still in alpha, BC breaks caused by upgrading should not be a concern. Do you plan to update prior to the first beta version?

**Comment by 24198** [comment]
Hi @sagikazarmark!

Thank you for your question! Yes we intent to update the Oro Platform version for Alpha 3, this probably will be Oro Platform 1.9.3. If while we are preparing for the future releases as well, we are probably going for version 1.10 in the Beta release.

This being said, we probably try to keep up with the Oro Platform version as close as we can, so we can leverage the latest and greatest from the platform. 

Hopefully this will answer your question :)

Kind Regards,

Jaimy Casteleijn

**Comment by sagikazarmark** [comment]
Hi @24198 

Yeah, it does. Actually I started to do some tests, but there are quite a few incompatibilities. If I have time, I will submit a few changes which you can reuse if I can't provide a full PR.

**Comment by 24198** [comment]
Hi @sagikazarmark,

I look forward to the changes and or PR. If you don't have time you are welcome to show some of the incompatibilities and we'll have a look at it :)

Kind Regards,

Jaimy Casteleijn

**Comment by 24198** [comment]
hi @sagikazarmark,

@gplanchat did great work with the migration to the Oro Platform 1.9 in PR #5, we will be reviewing this shortly and would include the migration to 1.9. If all things pass and are merged the will be in the next release of Marello. Once this is done, I'll come back and close this issue since the migration has been done :).

Kind Regards,

Jaimy Casteleijn

**Comment by gplanchat** [comment]
@24198 I did not migrate to 1.10 yet. There are still some fixes to apply on this version with 1.9, the UI breaks in some pages.

**Comment by sagikazarmark** [comment]
I would recommend migrating to 1.10 eventually, as it contains many bugfixes (like bugs with the session and api doc, etc)

**Comment by 24198** [comment]
Hi @sagikazarmark,

We'll probably move to 1.10 eventually, but taking the step to 1.9 is moving us closer to migrating to 1.10 :). So we'll do that eventually, but let's take small steps and move gradually towards 1.10.x.

Kind Regards,

Jaimy Casteleijn

**Comment by sagikazarmark** [comment]
Of course. What I really meant is as far as I know 1.10 contains many bug fixes (more than 1.9) which is a bigger benefit and I would consider taking that step too before a new release. AFAIK 1.10 does not contain that many BC breaks as previous versions (at least I didn't have as many problems as before)

**Comment by 24198** [comment]
Hi @sagikazarmark,

With the latest release, we've been able to move to 1.10.x instead of moving to 1.9 and do an update later to get to 1.10.x. I think this will conclude the issue about updating before the beta release I think. 

I will close the issue for now, if there us anything we might have missed, please reopen this issue or create a new one. 

Thank you both for being interested in Marello, we're looking forward to the future and it will bring.

Kind Regards,

Jaimy Casteleijn
