### ISSUE TITLE
Extend REST API

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#31]
Hello,

it would be very nice if you could extend the REST API for full REST support

e.g. Sales Channels, Tax etc.

**Comment by 24198** [comment]
Hi @clicktrend,

We're currently in the mode to move all of the current resources (Products, Orders etc..) to the JSON API which has some provided us with some challenges. We'll probably adding additional resources to them too, SalesChannels is probably one of them. We will less likely be adding additional resources to the current API since we'll be moving away from them in the future. You're more than welcome to add the additional resources and create a PR :).

Hope this helps,


Kind Regards,


Jaimy Casteleijn

**Comment by clicktrend** [comment]
I will wait for your new JSON API. Do you have a release time?

**Comment by 24198** [comment]
Hi @clicktrend,

New JSON API will probably be available in the next release which is due in September. This will include resources for Order, Product, Inventory, TaxCode, SalesChannels and some other entities too. 

Kind Regards,


Jaimy Casteleijn

**Comment by 24198** [comment]
Hi @clicktrend,

Our latest release, (https://github.com/marellocommerce/marello-application/releases/tag/1.5.0), features the newly added support for a majority of the entities. Hopefully this will help you with the data transfers in your business case.


Kind Regards,

Jaimy Casteleijn
