### ISSUE TITLE
Get Order from Shipment

### ISSUE THREAD

**Issue by NicolasCayet** [marellocommerce/marello#35]
Hello,

We have an association OneToOne from Marello\Bundle\OrderBundle\Entity\Order to Marello\Bundle\ShippingBundle\Entity\Shipment. So we can attach a Shipment to the Order, and get this Shipment from the Order.

Would it be possible to have a backward reference : getting an Order from the Shipment ?

**Comment by 24198** [comment]
Hi @NicolasCayet,

Thank you for asking and sorry for the late reaction. If my understanding is correct, you would like to have a backwards reference from the Shipment to the Order, a.k.a. a reference on the Shipment entity?

If my understanding is correct, than I have unfortunate news. We currently have no plans to create a reference on the Shipment entity for either entities related to them (Order and Return). We wanted to create the entity (Shipment) in a way where we can have a one directional relation with other entities (Order & Return) in order to prevent clutter. We might do something like this in the future, but as for now we don't have any plans for this.

In order to solve your problem, you could create a Repository or Provider which will look up the Shipment id in the Order table, this way you'll have your Order available when only having access to the Shipment.

Hopefully this helps and thank you for asking!

Kind Regards,


Jaimy Casteleijn
