### ISSUE TITLE
Purchase order grid error -> datagrids.yml marello-purchase-order-item-candidates failure

### ISSUE THREAD

**Issue by tirgil61** [marellocommerce/marello#62]
Replace line 168 

" - i.replenishment = 'never_out_of_stock' "

with
" - p.replenishment = 'never_out_of_stock' "

in file

Marello/Bundle/PurchaseOrderBundle/Resources/config/datagrid.yml

**Comment by 24198** [comment]
Hi @tirgil61,

Thank you for reporting. Can you please give us a little more information regarding the error and version of Marello you are currently running? 
We've tried to reproduce the issue with the latest version (3.0.1) and we are not experiencing the same.

Kind Regards,

Jaimy

**Comment by tirgil61** [comment]
Hi, 

i use version 3.0.1 updated from version 3.0.0

Steps to reproduce:
1. Purchase Order
2. Select Supplier
3. Add products from advice

--> Normally now the products should be shown which need to be ordered, because of the inventory 
=>(inventory - allocatedInventory) < purchaseInventory

But in the where clause line 168 there is the failure. 
In this case the field "replenishment" is not in table "marello_inventory_level", it is in table "marello_product_product".

If you change it from "i.replenishment" to "p.replenishment" the products are shown.

![old](https://user-images.githubusercontent.com/20697619/77400368-515b6200-6dab-11ea-9814-9c918598d96b.png)
![new](https://user-images.githubusercontent.com/20697619/77400374-55877f80-6dab-11ea-8209-a6b94ba62f54.png)

**Comment by 24198** [comment]
Hi @tirgil61. 
For reference and possible other users who might face the same issue I've put what we discussed regarding this issue as a comment.

The replenishment status is on neither product or inventory level. It should be on the InventoryItem which is what it’s trying to fetch. It used to be on the Product, but that was on a 1.x version if I recall correctly. If it’s still on the Product, some or more migrations might have not been executed correctly. The file `Marello\Bundle\InventoryBundle\Migrations\Schema\v1_2_2\AddColumnsToInventoryItem.php` is responsible for adding the Replenishment field on the InventoryItem which is where it should be in the 3.0.x version. If you have migrated from 1.x to 2.x to 3.x and this is not the case, you can check in the `oro_migrations` the versions of the Inventory Migrations and see if it should have been executed (aka the version is v2_4 now, so it should have been), if not it probably is not executed. A possible solution to this might be set a lower version than v1_2_2 and run `bin/console oro:platform:update --force --env=prod --bundles=MarelloInventoryBundle`, but this may cause other side effects.
Another possible solution is create a custom migration which will do the exact same thing as the v1_2_2 in order to fix the replenishment column.

Kind Regards,

Jaimy
